version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
      - REACT_APP_CRYPTO_SECRET=${CRYPTO_SECRET}
    restart: unless-stopped

  backend:
    image: mycloud-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - media:/app/media
      - static:/app/static

volumes:
  media:
  static:
